name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Oracle Cloud
      env:
        INSTANCE_IP: ${{ secrets.INSTANCE_IP }} 
      run: |
        SSH_USER="ubuntu"  # Mudar para o usuário correto
        
        ssh -o StrictHostKeyChecking=no $SSH_USER@$INSTANCE_IP << EOF
          # Verificar e criar o diretório se não existir
          if [ ! -d "~/oracle-cloud" ]; then
            echo "Diretório ~/oracle-cloud não existe. Criando..."
            mkdir -p ~/oracle-cloud
          fi

          cd ~/oracle-cloud || exit
          git reset --hard origin/master
          git pull origin master
          sudo docker-compose down
          sudo docker-compose up --build -d
        EOF
